// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNyEcBosNho0-IfOKtUGwnfyqReumDI0E',
    appId: '1:701923349470:web:60d8047b2ee725acb6034f',
    messagingSenderId: '701923349470',
    projectId: 'notebookapp-5c977',
    authDomain: 'notebookapp-5c977.firebaseapp.com',
    storageBucket: 'notebookapp-5c977.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvDoWUkvRf5NCDcl8Ol1a6N5OML5HClec',
    appId: '1:701923349470:android:d9e54063f97b225eb6034f',
    messagingSenderId: '701923349470',
    projectId: 'notebookapp-5c977',
    storageBucket: 'notebookapp-5c977.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiakp5fTrgobj9QRgX-yCfSlJgvtqZY7Y',
    appId: '1:701923349470:ios:39fe0aa2e6ff65cab6034f',
    messagingSenderId: '701923349470',
    projectId: 'notebookapp-5c977',
    storageBucket: 'notebookapp-5c977.appspot.com',
    iosBundleId: 'com.example.notebook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiakp5fTrgobj9QRgX-yCfSlJgvtqZY7Y',
    appId: '1:701923349470:ios:39fe0aa2e6ff65cab6034f',
    messagingSenderId: '701923349470',
    projectId: 'notebookapp-5c977',
    storageBucket: 'notebookapp-5c977.appspot.com',
    iosBundleId: 'com.example.notebook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNyEcBosNho0-IfOKtUGwnfyqReumDI0E',
    appId: '1:701923349470:web:e96ad0b533f00efdb6034f',
    messagingSenderId: '701923349470',
    projectId: 'notebookapp-5c977',
    authDomain: 'notebookapp-5c977.firebaseapp.com',
    storageBucket: 'notebookapp-5c977.appspot.com',
  );
}
